### ISSUE TITLE
client in node.js

### ISSUE THREAD

**Issue by ghost** [cvan/socketpeer#28]
Hi,
Is it possible to run webrtc client in node?
Thanks.

**Comment by cvan** [comment]
> Is it possible to run webrtc client in node?

That would require reimplementing the WebRTC protocol in Node. That's quite an undertaking, and socketpeer's client side is intended for use in a browser.

There are folks out there working on a Node implementation of WebRTC. Here's a popular one: https://github.com/js-platform/node-webrtc

Hope that helps. Thanks for asking!
